dotenv: .env

wallets:
    from_key: ${PRIVATE_KEY}

dependencies:
    # - smartcontractkit/chainlink-brownie-contracts@1.1.1
    - OpenZeppelin/openzeppelin-contracts@4.4.0
compiler:
    solc:
        remappings:
            # - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.0"

networks:
    default: ${DEFAULT_NETWORK:-development}

    development:
        default_config_network: rinkeby

    rinkeby:
        contracts:
            tokens:
                fau: "0xFab46E002BbF0b4509813474841E0716E6730136"
                link: "0x01BE23585060835E02B77ef475b0Cc51aA1e0709"
        config:
            verify: True
            # Example, Chainlink VRF keyhash parameter
            # vrf:
            #   keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
